### PR TITLE
add a count of cache hits and wpvulndb queries

### PR DESCRIPTION
**Pull request by cericoda**
Addresses #16 by returning a count of requests to wpvulndb.

### CODE REVIEW

**Comment by cericoda** [comment]
During testing, I also discovered the reason why I am getting more hits than expected - during plugin and theme checks, 404 responses from wpvulndb are not cached.. Do you think it's worth adding a feature request to cache the 404 response? I am not sure how the caching actually works, so not sure I will have time to learn how to implement.

**Comment by markri** [comment]
Caching 404's doesn't feel right. However I see your problem here... Not sure what to do...

**Comment by cericoda** [comment]
OK, sure, I get that in a way it doesn't feel right, but functionally, if you want to query every single time, just in case there has been a submission, then it's fine as it is . But if you think about it, you should cache a 404 response, as the purpose of caching is to remember the response, and that would include a not found response.

**Comment by markri** [comment]
Agreed, why not... There is the disadvantage of caching a temporary hickup (however that will restore a bit later, and metrics aren't mission critical in a sense that action is needed the minute the notification comes up. At least for us it is). But the advantage is that the plugin can be used more easily on a large scale for many implementations on one server without being banned by wpvulndb.

So yes, caching the 404 might be a good idea. Is this sitll something your would like to implement. Or would you like me to create an issue for that here on github untill I (or someone else) has time to fix this?

**Comment by cericoda** [comment]
Hi I'd be happy to implement it, however I had a quick dive and didn't really see how the caching was implemented, and wasn't sure if it would be overcomplicated to cache the 404 response. Is there any documentation on how this caching works? Is it a wpcli, php, or composer feature? Regarding an issue, I'd be happy to create one if you wanted.

**Comment by markri** [comment]
That shouldn't be too hard I guess. It uses the built in cache mechanism from wp-cli.

see: https://github.com/wp-cli/wp-cli/blob/d8f180e8abd0ebba950e1378dbf29174ad943f0e/php/class-wp-cli.php#L73

And https://github.com/markri/wp-sec/blob/master/command.php#L189 for its usage

I just created an issue for this #20

**Pull request merged**
