### PR TITLE
UPD extend JSON output with plugin/theme version and count

### PR DESCRIPTION
**Pull request by emaV**
Extend the JSON output to match the `OUTPUT_USER`:

```
{
  "plugins": {
    "count": N,
    "details": [
      {
         "title": "whatever",
         "status": "active",
         "version": "x.y.z",
         "count": N,
         "details": [
           {
             "fixed_in": "i.j.k"
...

### CODE REVIEW

**Comment by markri** [comment]
Superb!
Maybe you could add this new structure to a feature test? So we can test for BC.
I think the best approach is to simulate a dummy plugin/theme/core with a known vulnerabiltiy, so the new structure is filled in

**Comment by emaV** [comment]
Uhm, not an expert on wpvulndb but if you add an _old_ plugin/theme/core I'm wondering if we can be sure of the output. Maybe new vulnerabilities will break the test?

Or simply we can check for the output to be a well structured JSON, something like:

```
Then STDOUT should be JSON
```

without the _containing_ part.

Indeed I'm using this patch in my wp dashboard to get this page:

lenovo-emav___work

**Comment by markri** [comment]
Agreed, response content checking wouldn't me a smart move. However we could check the structure for the available keys like "title", "status", "version" etc. on a know vulnerability. And not checking the entire exact JSON. I'm no expert in behat, but I'm sure this is possible.

For now I merge the PR, and will create an issue for testing JSON output structure

**Comment by markri** [comment]
Cool dashboard BTW :-)
Did you built a custom WP plugin for output parsing?

Just curious about your wp-sec implementation

**Comment by emaV** [comment]
It's part of silex (symfony) application for managing wordpress site (dev/staging> production), kind of self hosted Pantheon. I plan to release the code once stable...

Basically the application lives in a server with the dev/staging wp sites and uses `wp-cli` to get the info and manage the updates. Then it leverages git to push the changes to the production.

As I didn't find a way to integrate wp-cli from the application I'm currently doing a lot of `exec("wp ...")`; I noticed you use `WP_CLI::launch_self(...)` but I don't know if it could work for me.

**Pull request merged**
